@startuml
'https://plantuml.com/activity-diagram-beta

start
:mob branch_name;
if (is working dir dirty?) then (yes)
  :raise WorkDirIsDirty();
  stop
endif

if (local branch_name exists) then (yes)
    if (remote/branch_name exists) then (yes)
        if (local branch_name ahead of remote) then (yes)
            :raise LocalBranchIsAheadOfOrigin();
            stop
        endif
    endif
endif

:git checkout branch_name;
note left
    Create the local branch
    if does not exist
end note

:git pull;
note left
    Create the local branch
    if does not exist
end note


' At this point we have local branch

'    else (no)
'        if (local branch_name exists) then (no)
'            :git checkout -b branch_name;
'        else (yes)
'            :git checkout branch_name;
'        endif
'
'        else (no)
'            :git checkout branch_name;
'            :git pull;
'
'else (no)
'    :git pull origin/branch_name;
'endif
'
'
':xss;

stop

@enduml
