@startuml
'https://plantuml.com/activity-diagram-beta

start
:create mob file;
note
  {
    branch: str,
    team: [
      null|driver|navigator: str,
    ],
    timerDuration: int=10,
  }
end note

:create local branch;
:push remote branch;
stop
@enduml
